package apparels.Modal;

public class SecurityEmail {
	public static String secure;
	
	public static String getSecure(String ip, String isp, String browser, String city,String region, String country, String lats,String longs,String date,String time,String day,String month) {
		secure ="<!DOCTYPE html>\r\n"
				+ "\r\n"
				+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "	<title></title>\r\n"
				+ "	<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n"
				+ "	<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n"
				+ "	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
				+ "	<!--[if !mso]><!-->\r\n"
				+ "	<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\" />\r\n"
				+ "	<!--<![endif]-->\r\n"
				+ "	<style>\r\n"
				+ "		* {\r\n"
				+ "			box-sizing: border-box;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		body {\r\n"
				+ "			margin: 0;\r\n"
				+ "			padding: 0;\r\n"
				+ "		\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		a[x-apple-data-detectors] {\r\n"
				+ "			color: inherit !important;\r\n"
				+ "			text-decoration: inherit !important;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		#MessageViewBody a {\r\n"
				+ "			color: inherit;\r\n"
				+ "			text-decoration: none;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		p {\r\n"
				+ "			line-height: inherit\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.desktop_hide,\r\n"
				+ "		.desktop_hide table {\r\n"
				+ "			mso-hide: all;\r\n"
				+ "			display: none;\r\n"
				+ "			max-height: 0px;\r\n"
				+ "			overflow: hidden;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		@media (max-width:620px) {\r\n"
				+ "			.desktop_hide table.icons-inner {\r\n"
				+ "				display: inline-block !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner {\r\n"
				+ "				text-align: center;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner td {\r\n"
				+ "				margin: 0 auto;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-content {\r\n"
				+ "				width: 100% !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				display: none;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.stack .column {\r\n"
				+ "				width: 100%;\r\n"
				+ "				display: block;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				min-height: 0;\r\n"
				+ "				max-height: 0;\r\n"
				+ "				max-width: 0;\r\n"
				+ "				overflow: hidden;\r\n"
				+ "				font-size: 0px;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.desktop_hide,\r\n"
				+ "			.desktop_hide table {\r\n"
				+ "				display: table !important;\r\n"
				+ "				max-height: none !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-1 .column-1 .block-5.paragraph_block td.pad>div,\r\n"
				+ "			.row-1 .column-1 .block-8.paragraph_block td.pad>div {\r\n"
				+ "				text-align: justify !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-1 .column-1 .block-5.paragraph_block td.pad,\r\n"
				+ "			.row-1 .column-1 .block-8.paragraph_block td.pad {\r\n"
				+ "				padding: 0 10px !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-1 .column-1 .block-6.list_block ul {\r\n"
				+ "				text-align: left !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-1 .column-1 .block-6.list_block ul {\r\n"
				+ "				line-height: auto !important;\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "	</style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body\r\n"
				+ "	style=\"background-color: transparent; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
				+ "	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\"\r\n"
				+ "		style=\"mso-table-lspace: 0pt; margin-top: 1%; mso-table-rspace: 0pt; background-color: transparent; background-image: none; background-position: top left; background-size: auto; background-repeat: no-repeat;\"\r\n"
				+ "		width=\"100%\">\r\n"
				+ "		<tbody>\r\n"
				+ "			<tr>\r\n"
				+ "				<td>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; border-top: 1px solid #030303; border-right: 1px solid #030303; border-left: 1px solid #030303; border-bottom: 1px solid #030303; width: 600px;\"\r\n"
				+ "										width=\"600\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"image_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\"\r\n"
				+ "																	style=\"line-height:10px\"><img alt=\"I'm an image\"\r\n"
				+ "																		src=\"https://i.ibb.co/0ZkQ9td/V-2-0b.png\"\r\n"
				+ "																		style=\"display: block; height: auto; border: 0; width: 150px; max-width: 100%;\"\r\n"
				+ "																		title=\"I'm an image\" width=\"150\" /></div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-2\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"font-family: 'Trebuchet MS', Tahoma, sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: 'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;\">\r\n"
				+ "																			<span\r\n"
				+ "																				style=\"font-size:22px;color:#000000;\"><strong>A\r\n"
				+ "																					Sign In Was Detected</strong></span>\r\n"
				+ "																		</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-3\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"font-family: 'Trebuchet MS', Tahoma, sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: 'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;\">\r\n"
				+ "																			<span\r\n"
				+ "																				style=\"font-size:18px;\"><strong>Someone@dsd.com</strong></span>\r\n"
				+ "																		</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-4\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #000000;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"paragraph_block block-5\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-left:10px;padding-right:10px;\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"color:#101112;direction:ltr;font-family:'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:150%;text-align:justify;mso-line-height-alt:24px;\">\r\n"
				+ "																	<p style=\"margin: 0; margin-bottom: 15px;\">\r\n"
				+ "																		<strong>We noticed a new sign-in to your WeenaLk\r\n"
				+ "																			account on "+browser+" Browser. If this was you,\r\n"
				+ "																			you don't need to do anything . If not\r\n"
				+ "																			please make sure to take secure your account\r\n"
				+ "																			. Our 24/7 support center will help you in\r\n"
				+ "																			any situations . Log in triggers were as\r\n"
				+ "																			follows</strong></p>\r\n"
				+ "																	<p style=\"margin: 0;\"> </p>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"list_block block-6\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<ul start=\"1\"\r\n"
				+ "																	style=\"margin: 0; padding: 0; margin-left: 20px; list-style-type: disc; color: #101112; direction: ltr; font-family: 'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif; font-size: 16px; font-weight: 700; letter-spacing: 0px; line-height: 120%; text-align: left;\">\r\n"
				+ "																	<ul\r\n"
				+ "																		style=\"margin: 0; padding: 0; list-style-type: disc; margin-top: 4px; margin-left: 30px;\">\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">IP :\r\n"
				+ "																			"+ip+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">ISP \r\n"
				+ "																			: "+isp+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Browser :\r\n"
				+ "																			"+browser+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">City :\r\n"
				+ "																			"+city+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Region :\r\n"
				+ "																			"+region+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Country :\r\n"
				+ "																			"+country+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Latitude :\r\n"
				+ "																			"+lats+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Longitude :\r\n"
				+ "																			"+longs+"</li>\r\n"
				+ "																		<li style=\"margin-bottom: 4px;\">Time :\r\n"
				+ "																			"+time+"</li>\r\n"
				+ "																		<li>Date : "+day+" "+month+" "+date+" </li>\r\n"
				+ "																	</ul>\r\n"
				+ "																</ul>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-7\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:25px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #000000;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"paragraph_block block-8\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-left:5px;padding-right:5px;\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"color:#101112;direction:ltr;font-family:'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif;font-size:15px;font-weight:400;letter-spacing:0px;line-height:150%;text-align:center;mso-line-height-alt:22.5px;\">\r\n"
				+ "																	<p style=\"margin: 0;\"><strong>Thank you for choosing\r\n"
				+ "																			WeenaLk the Best for The Quality product and\r\n"
				+ "																			Satisfaction, Be with Us for more\r\n"
				+ "																			Exclusives</strong></p>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"paragraph_block block-9\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-top:20px;\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"color:#101112;direction:ltr;font-family:'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif;font-size:10px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:12px;\">\r\n"
				+ "																	<p style=\"margin: 0;\"><strong><span\r\n"
				+ "																				id=\"6b176efd-5d3d-473e-aaef-8f4f97c127b2\">@2022\r\n"
				+ "																				WeenaLk</span></strong></p>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"paragraph_block block-10\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div\r\n"
				+ "																	style=\"color:#101112;direction:ltr;font-family:'Montserrat', 'Trebuchet MS', 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, sans-serif;font-size:10px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:12px;\">\r\n"
				+ "																	<p style=\"margin: 0;\"><strong><span\r\n"
				+ "																				id=\"6b176efd-5d3d-473e-aaef-8f4f97c127b2\">All\r\n"
				+ "																				Rights reserved</span></strong></p>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\"\r\n"
				+ "										width=\"600\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"icons_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\r\n"
				+ "																\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "		</tbody>\r\n"
				+ "	</table><!-- End -->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return secure;
	}
}
